### ISSUE TITLE
missing rules for filesystems metrics

### ISSUE THREAD

**Issue by Seb0042** [georou/prometheus-selinux#1]
Hi,

Missing some rules for filesystems metrics.
So far I added this:
allow node_prometheusd_exporter_t init_t:file read;
allow node_prometheusd_exporter_t init_t:file open;

But it's not enough, still have this message: 
node_exporter[7651]: time="2019-03-07T10:42:39+01:00" level=error msg="ERROR: filesystem collector failed after 0.000039s: open /proc/1/mounts: permission denied" source="collector.go:132"

The issue is that nothing is logged as avc in auditd... so can't see what is missing, if you have any idea ?

**Comment by georou** [comment]
Hi,

I would need some more information so I can replicate it on my system if you could, please.

1. What query are you trying to use? 
To confirm you're using the 'filesystem' collector or any other combination, such as 'mountstats'(disabled by default)?

2. Have you confirmed that node_exporter is running in the correct domain context? `ps -eZ | grep node_exporter`

If you aren't seeing anything further logged, you may need to disable the dontaudit rules: `semodule -DB` and try again. Don't forget to reverse that change after with `semodule -B`. More info about it [from Red Hat's handbook](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/selinux_users_and_administrators_guide/sect-security-enhanced_linux-troubleshooting-fixing_problems#sect-Security-Enhanced_Linux-Fixing_Problems-Possible_Causes_of_Silent_Denials)

**Comment by Seb0042** [comment]
Hi, after thinking a bit, I added the following and now it works:
allow node_prometheusd_exporter_t init_t:file read;
allow node_prometheusd_exporter_t init_t:file open;
allow node_prometheusd_exporter_t init_t:file getattr;
allow node_prometheusd_exporter_t init_t:dir search;

So to answer a your questions:
1) yes filesystem collector
2) yes the domain is correct when I do a ps:
system_u:system_r:node_prometheusd_exporter_t:s0 21685 ? 00:00:00 node_exporter

**Comment by georou** [comment]
Hi Seb,

I had some more time to dig deeper on Friday. I thought I had the latest node_exporter+prometheus but there was a newer one. I could then see the same errors as you had.

I've pushed the latest change to fix that. 

I see that they were indeed hidden. If you don't want to pull the latest, look at using the `init_read_state()` interface as it's cleaner and includes symlink files.

I'm not sure on your technical knowledge with selinux. If you're not sure what the interface contains, you can use the [macro-expander](https://lukas-vrabec.com/index.php/2019/02/03/new-trick-macro-expander/) if you're on RHEL, grep for it in /usr/share/selinux/devel/includes or [via github for RHEL](https://github.com/fedora-selinux/selinux-policy/blob/rawhide/policy/modules/system/init.if#L1344).

Thanks again for the heads up, appreciated!
